Lab 1

Exercise 1

In [29]:
#Create_arbitrarylist
def f(a, *arguments):
    print(a)
    for arg in arguments:
        print(arg)
f("A", "B", "C")

A
B
C


In [30]:
#Create_tuple
my_tuple = ()
print(my_tuple)

# Tuple having integers
my_tuple = (1, 2, 3)
print(my_tuple)

# tuple with mixed datatypes
my_tuple = (1, "Hello", 3.4)
print(my_tuple)

# nested tuple
my_tuple = ("mouse", [8, 4, 6], (1, 2, 3))
print(my_tuple)

()
(1, 2, 3)
(1, 'Hello', 3.4)
('mouse', [8, 4, 6], (1, 2, 3))


In [31]:
#Create_dictionary
my_dict = {1: 'Anastasiia', 2: 'Huska'}
print(my_dict)

{1: 'Anastasiia', 2: 'Huska'}


Exercise 2

In [32]:
import numpy as np
s = np.random.normal(0,1,100)
print(s[9])


1.843923236274512


In [33]:
print(s[9:19])

[ 1.84392324 -1.38326572 -0.52924537 -0.87785993  1.45120588  0.78291054
 -1.42289491  0.62933154 -1.9008668   0.40681305]


In [34]:
print(s[s>0])

[0.10237745 1.84392324 1.45120588 0.78291054 0.62933154 0.40681305
 1.695816   1.49213959 2.91731236 0.64253634 0.50052693 1.03236624
 0.13853016 1.07380664 0.51518277 0.62538889 0.37562723 0.06216382
 1.71692706 1.45704529 1.28605944 1.6656814  1.47736961 0.96374197
 0.88038137 0.00890096 0.71476165 0.60964703 2.08615576 1.38575649
 0.02447816 0.34632264 0.31070178 1.15110253 1.17242023 0.17371686
 0.67830986 2.3211682  1.26765925 1.58781417 1.37103415 0.37175975
 0.1535945  1.34698103 0.82373922 1.29462479 1.22597905]


Exercise 3

In [35]:
def mypow(base,power):
    if power<50:
        return base**power
    if power>=50:
        print ("Power is too big")
        return -1
  

print(mypow(2,2))
print(mypow(2,50))

4
Power is too big
-1


Exercise 4

In [36]:
import numpy as np
s = np.arange(20)


def above(x,n):
    for i in x:
        if x[i] > n:
            print(x[i], end=" ")
            
print(above(s, 10))

11 12 13 14 15 16 17 18 19 None


Exercise 5

In [37]:
import numpy as np
s = np.arange(20)

def my_ifelse(x, exp, n):
    if exp == ">":
       return x[x>n]
    if exp == "<":
       return x[x<n]
    if exp == ">=":
       return x[x>=n]
    if exp == "<=":
       return x[x<=n]
    if exp == "==":
       return x[x==n]
    else: return x

    
print(my_ifelse(s,">=",10))
print(my_ifelse(s,"<=",10))
print(my_ifelse(s,">",10))
print(my_ifelse(s,"<",10))
print(my_ifelse(s,"==",2))

[10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]
[2]


Exercise 6

In [38]:
def counter (input_string):
    count_letters = {}
    for letter in input_string:
        if letter in count_letters:
                count_letters[letter] += 1
        else:
            count_letters[letter] = 1
    return count_letters

print(counter("Ukraine"))

{'U': 1, 'k': 1, 'r': 1, 'a': 1, 'i': 1, 'n': 1, 'e': 1}


Exercise 7

In [39]:
def counter_sorted (input_string,reverse):
    a = {}
    for letter in sorted(input_string, reverse=reverse):
        if letter in a:
                a[letter] += 1 
        else:
            a[letter] = 1
    return a


print(counter_sorted("Ukraine",False))
print(counter_sorted("Ukraine",True))

{'U': 1, 'a': 1, 'e': 1, 'i': 1, 'k': 1, 'n': 1, 'r': 1}
{'r': 1, 'n': 1, 'k': 1, 'i': 1, 'e': 1, 'a': 1, 'U': 1}
